'use client' // Agregar la directiva para que sea un componente del cliente

import './globals.css'
// import type { Metadata } from 'next'

import { usePathname } from 'next/navigation' // Importar usePathname
import { LogOut } from 'lucide-react'
import { Inter } from 'next/font/google'
import Link from 'next/link'

import { MainNav } from '@/components/commons/main-nav'
import { NavMobile } from '@/components/commons/nav-mobile'
import { Button } from '@/components/ui/button'
import { CustomTooltip } from '@/components/commons/tooltip'
import ThemeToggle from '@/components/commons/theme-toggle'
import { ROUTES } from '@/consts/routes'

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app'
// }

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  const pathname = usePathname() // Obtener la ruta actual

  // Si la ruta es "/login", no renderizar el layout general
  if (pathname === '/login') {
    return (
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    )
  }

  // Layout general para otras rutas
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="sticky top-0 z-50 border-b backdrop-blur supports-[backdrop-filter]:bg-background/60">
          <div className="container flex h-16 w-full items-center justify-between gap-4 px-4 md:px-6">
            <MainNav />
            <NavMobile />
            <div className="flex w-fit items-center gap-4">
              {/* Menú de cambio de tema */}
              <ThemeToggle />
              <CustomTooltip content="Cerrar sesión">
                <Link className="flex items-center gap-4" href={ROUTES.LOGIN}>
                  <Button className="group rounded-full border-input/10 bg-border/10 hover:bg-transparent" size="icon" type="button" variant="outline">
                    <LogOut className="h-5 w-5 text-muted-foreground group-hover:text-secondary" strokeWidth={1.5} />
                  </Button>
                </Link>
              </CustomTooltip>
            </div>
          </div>
        </header>
        <main className="mx-auto flex min-h-[calc(100vh-4rem-1px)] w-full max-w-[auto] px-4 pt-6">{children}</main>
      </body>
    </html>
  )
}
