import './globals.css'
import type { Metadata } from 'next'

import { LogOut } from 'lucide-react'
import { Inter } from 'next/font/google'

import { MainNav } from '@/components/commons/main-nav'
import { NavMobile } from '@/components/commons/nav-mobile'
import { Button } from '@/components/ui/button'
import { CustomTooltip } from '@/components/commons/tooltip'
import ThemeToggle from '@/components/commons/theme-toggle'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="sticky top-0 z-50 border-b backdrop-blur supports-[backdrop-filter]:bg-background/60">
          <div className="container flex h-16 w-full items-center justify-between gap-4 px-4 md:px-6">
            <MainNav />
            <NavMobile />
            <div className="flex w-fit items-center gap-4">
              {/* Menú de cambio de tema */}
              <ThemeToggle /> {/* Usamos el componente separado */}
              <CustomTooltip content="Cerrar sesión">
                <Button className="group rounded-full border-input/10 bg-border/10 hover:bg-transparent" size="icon" type="button" variant="outline">
                  <LogOut className="h-5 w-5 text-muted-foreground group-hover:text-secondary" strokeWidth={1.5} />
                </Button>
              </CustomTooltip>
            </div>
          </div>
        </header>
        <main className="mx-auto flex min-h-[calc(100vh-4rem-1px)] w-full max-w-[1352px] px-4 pt-6">{children}</main>
      </body>
    </html>
  )
}
